package io.springui.compiler;

/**
 * JSInteropGenerator — generates the JavaScript glue layer
 * that bridges SpringUI's WebAssembly module with the browser DOM.
 *
 * When SpringUI compiles a component to WASM, the browser can't
 * directly call DOM APIs from WASM. This JS glue file:
 * 1. Loads the .wasm file
 * 2. Exposes browser DOM APIs to the WASM module
 * 3. Initializes SpringUI in the browser
 * 4. Mounts the root component
 *
 * Generated file is loaded via <script src="component.js"></script>
 */
public class JSInteropGenerator {

    // ===========================
    // Generate
    // ===========================

    /**
     * Generates the complete JS glue file for a compiled component.
     */
    public String generate(JSInteropConfig config) {
        StringBuilder js = new StringBuilder();

        appendHeader(js, config);
        appendDOMBindings(js);
        appendWasmLoader(js, config);
        appendSpringUIRuntime(js, config);
        appendBootstrap(js, config);

        return js.toString();
    }

    // ===========================
    // Header
    // ===========================

    private void appendHeader(StringBuilder js, JSInteropConfig config) {
        js.append("/**\n");
        js.append(" * SpringUI v").append(config.getFrameworkVersion()).append(" — JS Glue Layer\n");
        js.append(" * Component: ").append(config.getComponentName()).append("\n");
        js.append(" * Generated by SpringUICompiler — DO NOT EDIT\n");
        js.append(" */\n\n");
        js.append("'use strict';\n\n");
    }

    // ===========================
    // DOM Bindings
    // ===========================

    /**
     * Generates JS functions that WASM calls to manipulate the DOM.
     * These are the implementations of PatchApplier's DOM operations.
     */
    private void appendDOMBindings(StringBuilder js) {
        js.append("// DOM API bindings — called from WASM via imports\n");
        js.append("const springui_dom = {\n\n");

        // createElement
        js.append("  createElement: (tag) => {\n");
        js.append("    return document.createElement(tag);\n");
        js.append("  },\n\n");

        // createTextNode
        js.append("  createTextNode: (text) => {\n");
        js.append("    return document.createTextNode(text);\n");
        js.append("  },\n\n");

        // appendChild
        js.append("  appendChild: (parent, child) => {\n");
        js.append("    parent.appendChild(child);\n");
        js.append("  },\n\n");

        // removeChild
        js.append("  removeChild: (parent, child) => {\n");
        js.append("    if (child.parentNode) child.parentNode.removeChild(child);\n");
        js.append("  },\n\n");

        // setAttribute
        js.append("  setAttribute: (element, key, value) => {\n");
        js.append("    element.setAttribute(key, value);\n");
        js.append("  },\n\n");

        // removeAttribute
        js.append("  removeAttribute: (element, key) => {\n");
        js.append("    element.removeAttribute(key);\n");
        js.append("  },\n\n");

        // setTextContent
        js.append("  setTextContent: (node, text) => {\n");
        js.append("    node.nodeValue = text;\n");
        js.append("  },\n\n");

        // getElementById
        js.append("  getElementById: (id) => {\n");
        js.append("    return document.getElementById(id);\n");
        js.append("  },\n\n");

        // addEventListener
        js.append("  addEventListener: (element, event, callbackId) => {\n");
        js.append("    element.addEventListener(event, (e) => {\n");
        js.append("      springui_runtime.handleEvent(callbackId, e);\n");
        js.append("    });\n");
        js.append("  }\n\n");

        js.append("};\n\n");
    }

    // ===========================
    // WASM Loader
    // ===========================

    private void appendWasmLoader(StringBuilder js, JSInteropConfig config) {
        js.append("// WASM module loader\n");
        js.append("async function loadSpringUIWasm() {\n");
        js.append("  const response = await fetch('")
                .append(config.getWasmFileName()).append("');\n");
        js.append("  const bytes = await response.arrayBuffer();\n");
        js.append("  const { instance } = await WebAssembly.instantiate(bytes, {\n");
        js.append("    springui: springui_dom\n");
        js.append("  });\n");
        js.append("  return instance;\n");
        js.append("}\n\n");
    }

    // ===========================
    // SpringUI Runtime
    // ===========================

    private void appendSpringUIRuntime(StringBuilder js, JSInteropConfig config) {
        js.append("// SpringUI browser runtime\n");
        js.append("const springui_runtime = {\n\n");

        js.append("  instance: null,\n\n");

        js.append("  // Initialize the WASM instance\n");
        js.append("  init: async function() {\n");
        js.append("    this.instance = await loadSpringUIWasm();\n");
        js.append("    console.log('[SpringUI] WASM loaded successfully');\n");
        js.append("  },\n\n");

        js.append("  // Mount a component into a DOM element\n");
        js.append("  mount: function(componentId, targetElementId) {\n");
        js.append("    if (!this.instance) throw new Error('[SpringUI] Not initialized');\n");
        js.append("    this.instance.exports.springui_mount(componentId, targetElementId);\n");
        js.append("    console.log('[SpringUI] Mounted:', componentId);\n");
        js.append("  },\n\n");

        js.append("  // Handle events from DOM — routes back to WASM\n");
        js.append("  handleEvent: function(callbackId, event) {\n");
        js.append("    if (!this.instance) return;\n");
        js.append("    this.instance.exports.springui_handle_event(callbackId);\n");
        js.append("  },\n\n");

        js.append("  // Unmount a component\n");
        js.append("  unmount: function(componentId) {\n");
        js.append("    if (!this.instance) return;\n");
        js.append("    this.instance.exports.springui_unmount(componentId);\n");
        js.append("    console.log('[SpringUI] Unmounted:', componentId);\n");
        js.append("  }\n\n");

        js.append("};\n\n");
    }

    // ===========================
    // Bootstrap
    // ===========================

    private void appendBootstrap(StringBuilder js, JSInteropConfig config) {
        js.append("// Auto-bootstrap on DOM ready\n");
        js.append("document.addEventListener('DOMContentLoaded', async () => {\n");
        js.append("  try {\n");
        js.append("    await springui_runtime.init();\n");
        js.append("    springui_runtime.mount('")
                .append(config.getComponentName().toLowerCase())
                .append("', '").append(config.getMountElementId()).append("');\n");
        js.append("    console.log('[SpringUI] ")
                .append(config.getComponentName())
                .append(" mounted successfully');\n");
        js.append("  } catch (err) {\n");
        js.append("    console.error('[SpringUI] Bootstrap failed:', err);\n");
        js.append("  }\n");
        js.append("});\n");
    }
}